siderolabs/kres

.drone.yml
Makefile
internal/output/drone/step.go
internal/project/common/build.go
internal/project/common/image.go

Pushing `:latest` can be turned off via config.
Fixes #17
Fixes #15

feat: implement `make clean` and push `:latest`

---

Makefile
internal/output/makefile/group.go
internal/output/makefile/makefile_test.go
internal/output/makefile/variable.go
internal/project/auto/auto.go
internal/project/common/build.go
internal/project/common/image.go
internal/project/common/lint.go
internal/project/common/makehelp.go
internal/project/common/makehelp_test.go
internal/project/golang/build.go
internal/project/golang/gofumpt.go
internal/project/golang/golangcilint.go
internal/project/golang/unit_tests.go

Also fixed up some step descriptions.
Fixes #9

feat: generate 'make help' target

---

internal/project/auto/golang.go
internal/project/golang/toolchain.go
internal/project/meta/meta.go

This was required for `github.com/talos-systems/net` package.

feat: support for top-level Go source files

---

Makefile
cmd/kres/command/gen.go
hack/git-chglog/CHANGELOG.tpl.md
hack/git-chglog/config.yaml
hack/release.sh
internal/output/files.go
internal/output/preamble.go
internal/output/release/release.go

This adds the hack files for generating a release.
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>

feat: add release files

---

.dockerignore
.drone.yml
.markdownlint.json
Dockerfile
Makefile
README.md
cmd/kres/command/gen.go
hack/git-chglog/CHANGELOG.tpl.md
internal/output/files.go
internal/output/markdownlint/markdownlint.go
internal/project/auto/auto.go
internal/project/auto/builder.go
internal/project/auto/golang.go
internal/project/auto/markdown.go
internal/project/auto/utils.go
internal/project/markdown/lint.go
internal/project/markdown/markdown.go
internal/project/meta/meta.go

This does some refactoring to the automatic project builder,
incorporates new language "markdown" and required building blocks
for markdown-lint.

feat: add support for markdown linting

---

.drone.yml
internal/output/drone/drone.go
internal/output/drone/service.go
internal/output/drone/step.go
internal/output/drone/volume.go
internal/project/common/docker.go
internal/project/golang/toolchain.go

This allows those steps to be customized or thrown away depending on
the project. My first goal is to add support for setting resources on
docker service to limit number of builds per node.

refactor: extract default docker pipeline/volumes from the drone.Output

---

internal/project/common/docker.go

This is a small "hack" to prevent concurrent job runs on a single node.

feat: allow Docker service resource requests to be specified

---

.conform.yaml
cmd/kres/command/gen.go
internal/output/conform/conform.go
internal/output/conform/template.go
internal/project/common/repository.go

feat: add conform webhook

---

hack/git-chglog/config.yaml
internal/output/release/release.go
internal/project/common/build.go

fix: update repository name in release config

---

internal/project/common/repository.go

feat: invite talos-bot to the repository

---

internal/project/auto/git.go

Prefer `upstream` over `origin`, handle slash in remote path.

fix: detect remotes in more robust way

---

Dockerfile
Makefile
internal/project/common/docker.go
internal/project/common/input_image.go
internal/project/common/rekres.go
internal/project/golang/toolchain.go

This moves all the references to ghcr.io.

feat: switch default registry to ghcr.io

---

.drone.yml
internal/output/drone/step.go

fix: update the `docker login` step for ghcr.io

---

.drone.yml
internal/project/common/docker.go
internal/project/golang/unit_tests.go

This adjusts Drone builder creation and unit-tests step.

feat: provide an option to enable 'insecure' for buildkit in unit-tests

---

.golangci.yml
Dockerfile
internal/config/config.go
internal/output/dockerfile/dockerfile.go
internal/output/dockerfile/dockerfile_test.go
internal/output/golangci/config.go
internal/project/golang/golangcilint.go

Bump versions to match current tools versions.

feat: bump dockerfile frontend, golangci-lint

---

.golangci.yml
Dockerfile
Makefile
cmd/kres/command/meta.go
internal/config/config_test.go
internal/dag/base.go
internal/output/conform/conform.go
internal/output/dockerfile/dockerfile.go
internal/output/dockerfile/stage.go
internal/output/dockerfile/step/run.go
internal/output/drone/drone.go
internal/output/golangci/config.go
internal/output/golangci/golangci.go
internal/output/makefile/group.go
internal/output/makefile/target.go
internal/output/markdownlint/markdownlint.go
internal/output/release/release.go
internal/project/auto/config.go
internal/project/auto/git.go
internal/project/auto/golang.go
internal/project/common/all.go
internal/project/common/docker.go
internal/project/common/lint.go
internal/project/common/repository.go
internal/project/custom/custom.go
internal/project/golang/golangcilint.go
internal/project/golang/toolchain.go
internal/project/golang/unit_tests.go
internal/project/meta/meta.go
internal/project/service/codecov.go

feat: update Go to 1.16, markdown-lint to the latest release

---

internal/output/dockerfile/step/label.go
internal/output/dockerfile/step/step_test.go
internal/project/common/image.go

This links image back to the source repo.

feat: add image label with project source

---

internal/dag/dag.go
internal/project/auto/js.go
internal/project/golang/toolchain.go
internal/project/js/protobuf.go
internal/project/js/toolchain.go
internal/project/meta/meta.go
internal/project/project.go

Install `ts-proto` using npm and run `protoc` with that plugin enabled.

feat: generate protobuf for typescript projects

---

internal/project/js/unit_tests.go

It only makes the build to hang.

fix: do not output any artifacts in the frontend test

---

.conform.yaml
.drone.yml
Dockerfile
Makefile
hack/release.sh
hack/release.toml
internal/output/dockerfile/dockerfile.go
internal/output/dockerfile/stage.go
internal/output/drone/step.go
internal/output/files.go
internal/output/release/release.go
internal/project/auto/builder.go
internal/project/common/build.go
internal/project/common/image.go
internal/project/common/release.go
internal/project/common/repository.go
internal/project/golang/build.go
internal/project/markdown/lint.go
internal/project/meta/meta.go

Replace old release scripts with the same release tool which is already
used in Talos and Sidero.
Also add support for Go cross compilation.

feat: use release tool

---

cmd/kres/command/meta.go
internal/config/config.go
internal/config/config_test.go
internal/dag/base.go
internal/dag/dag.go
internal/output/dockerfile/dockerfile.go
internal/output/dockerfile/dockerfile_test.go
internal/output/dockerfile/stage.go
internal/output/drone/consts.go
internal/output/drone/drone.go
internal/output/files.go
internal/output/makefile/makefile_test.go
internal/project/auto/git.go
internal/project/auto/golang.go
internal/project/auto/js.go
internal/project/common/all.go
internal/project/common/docker.go
internal/project/common/lint.go
internal/project/common/repository.go
internal/project/custom/custom.go
internal/project/golang/toolchain.go
internal/project/golang/unit_tests.go
internal/project/meta/meta.go

chore: fix style of `//nolint` directives

---

.conform.yaml
.kres.yaml
internal/output/conform/conform.go
internal/output/conform/conform.yaml
internal/project/common/repository.go

And enable it by default.
Co-authored-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>

feat: make GPG signature checking configurable

---

Dockerfile
Makefile
cmd/kres/command/gen.go
go.mod
go.sum
internal/project/golang/gofumpt.go
internal/project/golang/golangcilint.go

Keeping our toolchain up to date.

feat: update Go 1.17, golangci-lint to 1.42.1

---

Dockerfile
Makefile
hack/release.sh
internal/output/release/release.sh
internal/project/common/input_image.go
internal/project/common/rekres.go
internal/project/golang/toolchain.go

Update base image references, release-tool image, reference to kres
itself.

feat: update more references to talos-systems

---

cmd/kres/main.go
go.mod
internal/dag/node.go
internal/output/drone/drone.go
internal/project/auto/git.go
internal/project/common/all.go
internal/project/common/image.go
internal/project/common/lint.go
internal/project/custom/custom.go
internal/project/golang/build.go
internal/project/golang/toolchain.go
internal/project/golang/unit_tests.go
internal/project/js/build.go
internal/project/js/toolchain.go
internal/project/js/unit_tests.go
internal/project/service/codecov.go

Redo `dag.Implements` as Go 1.18 generic function.

Redo implements

---

internal/project/golang/generate.go

It should run even when protobufs are not used.

fix: issues with go generate

---

internal/project/js/templates/eslint.yaml

The update was required after the update of dependencies in the UI
projects.

chore: update eslint rules

---

internal/project/custom/custom.go

Now `kres` supports `docker` configs.
It is possible to define: `arg`, `script`, `copy` steps.
Cache is also supported.
This step kind can help building integration tests targets and such.

feat: support docker custom steps

---

internal/project/js/build.go

Makefiles generated by kres now accept a NODE_BUILD_ARGS variable and
pass its contents on to the 'npm run build' command.
Signed-off-by: Philipp Sauter <philipp.sauter@siderolabs.com>

feat: add ability to pass node build arguments to npm build steps

---

.github/renovate.json
internal/config/constants.go

Package renovate PR's into groups.
Make conformance happy

chore: package into groups

---

.github/renovate.json
internal/config/constants.go
internal/project/common/docker.go

- Update renovate config
- Add updates for dind

chore: update aqua config

---

.drone.yml
internal/output/drone/drone.go

Disable running pipeline for renovate/dependabot pull requests.

chore: disable drone for renovate/dependabot

---

.drone.yml
internal/output/drone/drone.go

Fixes slack notifications not being triggered on failures. This was introduced by #162, partially revert back.

fix: no slack notifications on failure

---

Dockerfile
Makefile
internal/project/auto/golang.go
internal/project/golang/govulncheck.go
internal/project/golang/govulncheck_test.go

Add govulncheck to Go linters.

feat: add govulncheck to go linters

---

Dockerfile
Makefile
internal/output/makefile/condition.go
internal/output/makefile/makefile.go
internal/output/makefile/makefile_test.go
internal/output/makefile/variable.go
internal/project/common/build.go
internal/project/common/docker.go
internal/project/golang/build.go
internal/project/golang/toolchain.go

This copies the flow from Talos.
Fixes #88
Replaces #172

feat: implement support for WITH_DEBUG & WITH_RACE

---

cmd/kres/cmd/gen.go
internal/output/codecov/codecov.go
internal/output/conform/conform.go
internal/output/dockerfile/dockerfile.go
internal/output/drone/drone.go
internal/output/github/github.go
internal/output/gitignore/gitignore.go
internal/output/golangci/golangci.go
internal/output/license/license.go
internal/output/makefile/makefile.go
internal/output/markdownlint/markdownlint.go
internal/output/output.go
internal/output/release/release.go
internal/output/template/template.go

Redo implementations to remove type assertions in each type implementing Writer.

chore: add type safe wrapper for output.Writer

---

Dockerfile
internal/config/constants.go

chore: bump deps

---

README.md

This is a silly one that tripped me up for a minute just now. So quick
readme update.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>

chore: update readme with correct image name

---

internal/project/common/repository.go

fix: use new GitHub API for PR status checks

---

go.mod
go.sum
internal/output/github/github.go
internal/project/common/repository.go

Missed bumping github.com/google/go-github to v51

chore: bump go-github

---

internal/config/constants.go

Features:
- https://github.com/siderolabs/protoc-gen-grpc-gateway-ts/pull/4

chore: bump protobuf-ts-gateway version

---

Dockerfile
internal/config/constants.go

chore: bump node to 20.2.0-alpine3.17

---

internal/project/golang/generate.go
internal/project/meta/meta.go

This will be useful for improving ResourceSpec.DeepCopy performance in github.com/cosi-project/runtime.

chore: add clone generator to vtproto

---

Makefile
internal/config/constants.go
internal/project/golang/gofumpt.go

I forgot to update those things in previous [PR](https://github.com/siderolabs/kres/pull/273).

chore: update GO_VERSION and fmt target

---

.github/workflows/ci.yaml

This PR moves to using the "pull_request_target" as well as an if statement to ensure the slack notifications work by default.

chore: update no-op github workflow

---

.github/workflows/ci.yaml

This reverts commit b68543debf1a74dae05db0eeea4b52b6ddcae755.

chore: revert b68543debf1a74dae05db0eeea4b52b6ddcae755.

---

.github/workflows/ci.yaml
internal/output/ghworkflow/gh_workflow.go

Skip pull requests by dependabot/renovate.

chore: skip renovate/dependabot pull requests

---

.github/workflows/ci.yaml
internal/output/ghworkflow/gh_workflow.go

Add preamble to the generated GitHub workflow yaml.

chore: gh workflow preamble

---

internal/project/common/docker.go

Only set `CI_ARGS` for GitHub actions.

chore: only set CI_ARGS for ghactions

---

.github/workflows/slack-notify.yaml
internal/output/ghworkflow/gh_workflow.go

Skip slack notification for skipped workflows.

fix: skip slack notify for skipped workflows

---

.github/workflows/ci.yaml
Dockerfile
internal/config/constants.go
internal/output/ghworkflow/gh_workflow.go
internal/project/custom/custom.go

Fix workflow run being triggered on renovate branches.
Also bump deps.

fix: worflow run on renovate branches

---

.golangci.yml
internal/output/golangci/golangci.yml

Both of those produce false positives.

chore: disable 'testifylint' and 'protogetter' linters

---

Makefile
internal/project/common/release.go

For api projects only publish RELEASE notes.

fix: release for api only projects

---

Makefile
internal/project/common/rekres.go

chore: rekres as local user

---

internal/project/custom/custom.go

Save job logs if artifacts are defined.

chore: save job logs

---

internal/project/pkgfile/build.go

This supports projects that uses `bldr eval` to retrieve version tag. In our case it's the extensions repo.
Also fixes a bug in GH workflow generation where `additionalTargets` was missed during CI build and push.

chore: support bldr eval projects

---

internal/project/auto/config.go
internal/project/golang/generate.go

To fetch something and use in go build.

feat: allow adding arbitrary files in `golang.Generate` step

---

internal/output/dockerfile/stage.go
internal/output/dockerfile/step/copy.go
internal/project/common/docker.go
internal/project/common/image.go
internal/project/custom/custom.go
internal/project/golang/toolchain.go

Support more customization of options.

chore: support more customization

---

internal/project/golang/toolchain.go
internal/project/pkgfile/build.go

Support for customization for `Pkgfile` based repos.

chore: support more customization for Pkgfile

---

internal/output/files.go

`Dockerfile` was getting written everytime without the fix even if contents has not been changed.

fix: dockerfile preamble handling

---

internal/config/constants.go

chore: bump bldr to v0.3.0

---

internal/project/auto/golang.go
internal/project/auto/pkgfile.go
internal/project/common/docker.go

Git repo operations were not handled for Pkgfile previously, now handle it correctly.
Fixes: #370

fix: git repo handling

---

.github/workflows/ci.yaml
internal/output/ghworkflow/gh_workflow.go
internal/project/common/image.go

Avoids pushing latest from e.g. release branches.

fix: run GHA push-latest only from 'main' branch

---

cmd/kres/cmd/gen.go
go.mod
go.sum
internal/config/constants.go
internal/output/ghworkflow/gh_workflow.go
internal/output/github/github.go
internal/output/sops/sops.go
internal/project/auto/builder.go
internal/project/common/repository.go
internal/project/common/sops.go
internal/project/custom/custom.go

feat: add sops support

---

.github/workflows/ci.yaml
Dockerfile
internal/output/ghworkflow/gh_workflow.go

Fail pipeline if secrets cannot be used.

fix: fail pipeline on yq error

---

internal/project/golang/unit_tests.go

Support Docker `COPY` steps for lint target.

chore: support docker copy steps for lint target

---

internal/project/common/gh_workflow.go

Allow conditions for registry login step.

fix: allow conditions for registry login step

---

.github/workflows/ci.yaml
internal/config/constants.go
internal/output/ghworkflow/gh_workflow.go
internal/project/common/gh_workflow.go

Support printing system info.
Also fix step conditions for artifact steps.

chore: system info

---

Dockerfile
go.mod
go.sum
internal/config/constants.go

feat: update dependencies (buildkit, dockerfile)

---

internal/project/pkgfile/build.go

Setting conditions for pkgfile extra targets was missed.

fix: pkgfile extra targets

---

hack/release.sh
internal/output/release/release.sh

Update the year and the date when we do `./hack/release.sh commit <TAG>`.
Requirement for https://github.com/siderolabs/omni/issues/557.

feat: update dates in BUSL license on release commit

---

internal/output/release/release.sh

Update the BUSL change date in `.kres.yaml` like we do in the LICENSE files on release commits, so the date doesn't get reverted when the project is re-kres'd.

feat: update dates in BUSL license on release commit in `.kres.yaml`

---

internal/project/auto/js.go
internal/project/js/toolchain.go

fix: add all `*.ico` files in the frontend repo to the builder image

---

Makefile
internal/project/common/docker.go
internal/project/pkgfile/build.go

Use `$DEST` as it's the actual output location, and apply fixups there.

fix: use correct output variable

---

.github/workflows/slack-notify.yaml
internal/output/ghworkflow/gh_workflow.go

fix: slack notification, take 2

---

.github/renovate.json
.kres.yaml
internal/output/renovate/types.go
internal/project/common/renovate.go

Add more renovate config fields.

chore: add more renovate config fields

---

internal/config/constants.go

See https://github.com/siderolabs/bldr/releases/tag/v0.4.1

feat: update bldr to v0.4.1

---

internal/config/constants.go

New pkgs needed for new rootfs structure
Signed-off-by: Dmitry Sharshakov <dmitry.sharshakov@siderolabs.com>

chore: bump Go and pkgs

---

Dockerfile
internal/config/constants.go

Fixes ca-certificates access permissions
Signed-off-by: Dmitry Sharshakov <dmitry.sharshakov@siderolabs.com>

chore: bump pkgs

---

.github/renovate.json
.kres.yaml
Dockerfile
internal/config/constants.go
internal/output/renovate/types.go
internal/project/common/renovate.go
internal/project/pkgfile/build.go

Use new `managerFilePatterns`.
Also update deps.

feat: migrate renovate config

---

internal/project/custom/custom.go

fix: support retention days for all artifact types

---

.github/workflows/slack-notify.yaml
internal/output/ghworkflow/files/slack-notify-payload.json
internal/output/ghworkflow/gh_workflow.go

Change channel name as well.
Part of #357

feat: move notifications to different Slack instance

---

.github/workflows/slack-notify.yaml
internal/output/ghworkflow/files/slack-notify-payload.json

Use a custom emoji as an icon, fix fallback text used in notifications.

fix: notify Slack formatting

---

.github/workflows/slack-notify.yaml
internal/output/ghworkflow/files/slack-notify-payload.json

fix: attempt to fix Slack payload

---

.dockerignore
Dockerfile
Makefile
hack/govulncheck.sh
internal/output/dockerfile/step/copy.go
internal/project/golang/generate.go
internal/project/golang/govulncheck.go
internal/project/golang/templates/govulncheck.sh
internal/project/golang/templates/templates.go
internal/project/golang/toolchain.go

This wrapper enables excluding vulnerabilities to pass scans, if we are unaffected.
Signed-off-by: Mateusz Urbanek <mateusz.urbanek@siderolabs.com>

feat: add govulncheck wrapper

---

Makefile
internal/project/golang/toolchain.go

Remove default synctest value from GOEXPERIMENT

chore: remove default synctest value from GOEXPERIMENT

---

internal/config/constants.go
internal/project/pkgfile/build.go

Also bump bldr to v0.5.3 enable build args.

feat: update bldr to generate package dependencies in SVG

---

internal/project/auto/js.go

Add the frontend/msw directory to docker containers
Related PR
- https://github.com/siderolabs/omni/pull/1605

chore: add frontend/msw directory to docker

---

.github/renovate.json
.kres.yaml
internal/config/constants.go

Fix invalid version scheme for node version

chore: fix invalid version scheme for node version
