- .drone.yml
- Makefile
- internal/output/drone/step.go
- internal/output/makefile/makefile_test.go
- internal/output/makefile/target.go
- internal/output/makefile/variable.go
- internal/project/common/image.go
`TAG` is a simple variable to avoid multiple lookups of `$(shell ...)`,
so it has to be overridden on command line (vs. via environment
variables).
Clean up some trailing whitespace in Makefiles.
> fix: override tag correctly in push-latest

- .codecov.yml
- .drone.yml
- Makefile
- cmd/kres/command/gen.go
- internal/output/codecov/codecov.go
- internal/output/codecov/template.go
- internal/output/drone/step.go
- internal/project/auto/golang.go
- internal/project/common/all.go
- internal/project/service/codecov.go
- internal/project/service/codecov_test.go
- internal/project/service/service.go
- internal/project/wrap/drone.go
- internal/project/wrap/drone_test.go
- internal/project/wrap/wrap.go
This includes generation of `.codecov.yml`, targets in Makefile and
Drone build, etc.
Fixes #2
> feat: implement code coverage support

- Dockerfile
- internal/project/common/image.go
This allows container image to be built from e.g. `alpine:3.11` with
some custom `apk add` commands.
> feat: allow base image to be customized

- internal/project/auto/golang.go
- internal/project/golang/toolchain.go
- internal/project/meta/meta.go
For libraries it doesn't make sense to have a layout with
`pkg/` and `internal/`, so we need to support that.
> feat: provide support for non-standard Go package layout

- Dockerfile
- internal/project/golang/build.go
- internal/project/golang/golangcilint.go
- internal/project/golang/toolchain.go
- internal/project/golang/unit_tests.go
- internal/project/meta/meta.go
In Go 1.15 there's separate environment variable to control the cache
locaiton: https://github.com/golang/go/issues/34527, but as we're on Go
1.14 yet, we use compatible approach with `GOPATH/pkg` being cached
across all Go-related build steps.
This speeds up `go mod download` a lot when only some module
dependencies got changed.
> feat: add cache volume for GOMODCACHE location

- Dockerfile
- internal/project/golang/toolchain.go
This step also depends on module cache.
> fix: push go module cache to go mod list

- internal/project/auto/config.go
- internal/project/auto/golang.go
Sometimes we don't need an image for the command, allow image to be
skipped.
> feat: allow image build to be skipped

- hack/release.sh
- internal/output/release/release.go
This PR fixes a small bug in release.sh where we weren't starting our
alpha counting from *.0.
> fix: ensure we start alphas a alpha.0 version

- internal/dag/dag.go
- internal/output/drone/step.go
- internal/output/makefile/group.go
- internal/project/auto/builder.go
- internal/project/auto/config.go
- internal/project/auto/custom.go
- internal/project/custom/custom.go
Sometimes we need custom steps specific to the project, which can't be
derived from the project structure: e.g. running integration tests.
> feat: support custom steps in Makefile/Drone

- internal/project/custom/custom.go
Steps in Kres usually discover whether they should record Drone
dependency on each other via the interfaces (whether parent interface
implements Drone interface), but custom steps always implement Drone
interface, but Drone step generation is controlled by the config, so
handle this case explicitly.
Discovered in Sfyra.
> fix: make custom steps put correct Drone dependencies

- Makefile
- internal/project/golang/toolchain.go
This applies to any Kres-controlled project (after `rekres`).
> feat: bump default Go toolchain version to 1.15.x

- internal/project/common/repository.go
We no longer use this with talos-bot.
> fix: remove status-lgtm from the list of required statuses

- .drone.yml
- .golangci.yml
- Dockerfile
- internal/output/golangci/config.go
- internal/project/auto/markdown.go
- internal/project/golang/golangcilint.go
This forces build to run only on `ci` nodes.
> feat: bump golangci-lint

- internal/output/conform/conform.go
- internal/output/conform/template.go
- internal/output/license/license.go
- internal/project/common/repository.go
This allows Kres to skip LICENSE thing if configure to do so.
(used in talos-systems/release-tool)
> feat: add an option to disable license checks and enforcement

- Dockerfile
- Makefile
- internal/output/dockerfile/step/add.go
- internal/output/dockerfile/step/step_test.go
- internal/project/auto/golang.go
- internal/project/golang/build.go
- internal/project/golang/protobuf.go
- internal/project/golang/toolchain.go
`.proto` files are added explicitly via the `.kres.yaml`, copied from
exeternal "spec" repo, compiled to Go and available for the use.
Example:
```
kind: golang.Protobuf
spec:
experimentalFlags:
- --experimental_allow_proto3_optional
specs:
- source: https://raw.githubusercontent.com/smira/specification/resource-proto/proto/v1alpha1/resource/resource.proto
subdirectory: v1alpha1/
```
> feat: add support for .proto files and compilation

- Dockerfile
- internal/project/golang/unit_tests.go
This both tracks coverage for all packages, even those which don't have
tests, and also tracks coverage when test of one package touches other
packages.
> feat: add `coverpkg` to `go test` to produce full coverage

- internal/project/auto/js.go
- internal/project/js/toolchain.go
- internal/project/meta/meta.go
Different fronentd projects may have different set of config files
defined in the *.js files in the root of the project.
They should be automatically copied into build root directory.
> feat: add all *.js files in the root of the frontend project

- internal/project/common/docker.go
Makes things a bit less talos-systems centric.
> feat: set the `USERNAME` to the GitHub org

- internal/project/js/templates/eslint.yaml
Otherwise it's using rules from Vue 2 and the compiler and linter fight
with each other.
> fix: use vue3 rules as we use Vue 3 in our projects

- internal/output/conform/template.go
- internal/project/golang/gofumpt.go
- internal/project/golang/protobuf.go
- internal/project/js/build.go
- internal/project/js/protobuf.go
- internal/project/js/toolchain.go
gRPC gateway server wrappers are enabled by `genGateway` flag for each
particular spec.
> feat: enable gRPC gateway files generation

- internal/project/js/protobuf.go
Generated clients compile only for Node.js, not for TypeScript running
on the web page.
> feat: disable gRPC client generation for TypeScript

- internal/project/js/protobuf.go
Otherwise it converts `tail_events` to `tailEvents` and serializes it to
JSON like that.
Go protobuf JSON tags are defined in snake case.
> fix: disable snakeToCamel flag for TS protobuf generation

- internal/project/js/protobuf.go
To avoid defining it for each spec. Practice shows that it's not really
necessary to define a unique folder for each spec.
> feat: add the top level definition for dest dir of TS proto generator

- .dockerignore
- .golangci.yml
- Dockerfile
- Makefile
- internal/output/codecov/codecov.go
- internal/output/golangci/golangci.go
- internal/output/golangci/golangci.yml
- internal/project/golang/gofumpt.go
- internal/project/golang/golangcilint.go
- internal/project/js/protobuf.go
- internal/project/js/templates/templates.go
* disable new tagliatelle linter;
* sort disabled linters;
* move template to separate file;
* use `go install` for installing tools.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
> feat: update golangci-lint and its configuration

- .drone.yml
- .golangci.yml
- internal/output/golangci/golangci.yml
- internal/project/common/docker.go
Usefullness of this linter is questionable and we already have this
linter disabled in Talos, so we're not following that pattern in most of
the projects.
It only prohibits usage of `replace` in `go.mod`, but it looks like
using is inevitable right now in all our projects.
> chore: update docker to 20.10 and disable some linters

- cmd/kres/command/gen.go
- internal/project/golang/toolchain.go
- internal/project/js/toolchain.go
- internal/project/meta/meta.go
Previosly, go was installed into protobuf container using `apk add go`,
which installs go `1.15`, which does not support `go install
path@version` syntax.
> fix: use the same go version both in js protobuf as in go toolchain

- internal/project/js/toolchain.go
As we now have dev server mode this `node_modules` folder might exist
locally, so it should be added to `.gitignore`.
> fix: add `frontend/node_modules` to gitignore

- internal/output/template/template.go
- internal/project/golang/build.go
- internal/project/js/toolchain.go
- internal/project/js/unit_tests.go
- internal/project/js/unit_tests_test.go
Looks like it was broken after the last attempt to fix `multiple
executables` x `multiple build settings` support.
Also generate `tsconfig.json`, `babel.config.js` and `jest.config.js`
into the `frontend` folder now and do not overwrite them ever.
They may be project specific and it's easier to change them manually.
> fix: set build options for each go build target

- .conform.yaml
- Dockerfile
- Makefile
We need to update `.git/config` to change the upstream/origin URL to use
`siderolabs` org and Kres will take care about the rest.
> chore: update kres to use new org name

- Dockerfile
- Makefile
- internal/project/auto/golang.go
- internal/project/golang/gofumpt.go
- internal/project/golang/goimports.go
- internal/project/golang/goimports_test.go
- internal/project/golang/protobuf.go
Fixes #87
This is a bunch of changes:
* update `vtprotobuf` to the release version which fixes some bugs
* update `gofumpt`, as it is missing `gofumports` now, add `goimports`
* generate as many specs as possible in a single `protoc` run, as
otherwise it casuses problem for `vtprotobuf` when all generared files
are going to the same Go package (duplicate declarations)
* format generated protobuf files
> feat: vtprotobuf bump, protoc aggregation, gofumpt + goimports

- internal/output/drone/step.go
- internal/project/auto/git.go
- internal/project/common/image.go
- internal/project/common/repository.go
- internal/project/meta/meta.go
Previously we defaulted to the main branch name "master". However many projects use "main" or "develop" as their main branch name and we add support by detecting the main branch of the origin remote from .git/config.
Fixes #84
Signed-off-by: Philipp Sauter <philipp.sauter@siderolabs.com>
> feat: detect main branch name

- internal/output/license/license.go
- internal/project/auto/golang.go
- internal/project/common/repository.go
- internal/project/golang/generate.go
The `golang.Protobuf` step was renamed to `golang.Generate`. The
projects using `golang.Protobuf` should get the config update.
Generator can be configured by the following section:
```yaml
...
golang.Generate:
goGenerateSpecs:
- source: ./ # the root folder of the project
copy:
- internal/app/
```
> feat: support running go generate

- internal/project/golang/generate.go
COSI has "external" specs, but they're internal as they live in the same
package. This fixes gRPC-Gateway generation for COSI.
> feat: allow to specify external for proto file explicitly

- .golangci.yml
- internal/output/golangci/golangci.yml
This linter is not really useful, and has lots of false alerts when
using the Go cache.
> fix: disable `ireturn` linter

- Dockerfile
- internal/project/common/input_image.go
- internal/project/js/eslint.go
- internal/project/js/protobuf.go
- internal/project/js/toolchain.go
- internal/project/markdown/lint.go
Bump base node version to v18.4.0
Also bump ts-proto and protoc-gen-grpc-gateway-ts
> chore: bump base node to v18.4.0

- internal/output/drone/step.go
- internal/project/custom/custom.go
This is needed when we run huge workloads in the integration tests.
> feat: allow resource requests for custom Drone steps

- internal/project/js/protobuf.go
Without the option it imports `Long` type incorrectly which renders
generated files unusable in the web based TypeScript.
> fix: add an option to ts-proto generator which fixes JS compilation

- Dockerfile
- internal/project/js/toolchain.go
- internal/project/markdown/lint.go
> chore: bump node to v18.6.0

- Dockerfile
- internal/project/js/toolchain.go
- internal/project/markdown/lint.go
> chore: bump node to v18.7.0

- internal/project/common/docker.go
Add `REGISTRY` variable to build args.
> chore: add `REGISTRY` to build args

- internal/project/custom/custom.go
Support setting `environment` for drone.
> chore: support setting `environment` for drone

- Dockerfile
- Makefile
- internal/project/common/image.go
- internal/project/golang/toolchain.go
Support building cross platform go binaries.
Suport setting custom drone Environment for images.
Eg:
```yaml
---
kind: common.Image
name: image-<app>
spec:
pushLatest: false
droneExtraEnvironment:
PLATFORM: linux/amd64,linux/arm64
---
kind: golang.Build
spec:
outputs:
linux-amd64:
GOOS: linux
GOARCH: amd64
linux-arm64:
GOOS: linux
GOARCH: arm64
```
> chore: support go cross builds

- internal/project/golang/build.go
Changed the config format.
Before:
```yaml
golang.Build:
outputs:
linux-amd64:
GOOS: linux
GOARCH: amd64
```
After:
```yaml
golang.Build:
outputs:
linux-amd64:
env:
GOOS: linux
GOARCH: amd64
include: executable-name
exclude: another-executable-name
buildFlags:
- "-tags sidero.debug"
```
Now it's possible to filter the executables based on the name and set
their build flags.
> feat: support setting build flags and filter executables in golang build

- .drone.yml
- internal/output/drone/drone.go
The slack trigger was already having status set in the step itself, so
remove that and only use the trigger. Follow up of https://github.com/siderolabs/kres/pull/161#issuecomment-1248157563
> chore: disable drone slack pipeline

- .drone.yml
- internal/output/drone/drone.go
The slack trigger was already having status set in the step itself, so remove that and only use the trigger.
Previous PR #163 set it at the wrong level :facepalm
> chore: disable drone slack pipeline for renovate

- internal/project/auto/golang.go
Allow go files to be absent from the root directory.
> fix: allow Go non-standard layouts

- internal/project/js/templates/templates.go
Reformat the comment to be gofmt 1.19 compatible, so it doesn't fail on linting.
Signed-off-by: Utku Ozdemir <utku.ozdemir@siderolabs.com>
> fix: reformat comment on frontend.go to pass linters

- internal/project/auto/git.go
If a branch is named "main", detect the main git branch to be it even if its remote is not named as "origin".
Fixes siderolabs/kres#182.
Signed-off-by: Utku Ozdemir <utku.ozdemir@siderolabs.com>
> fix: detect main branch correctly when remote name is not origin

- internal/dag/node.go
- internal/output/drone/drone.go
- internal/project/common/all.go
- internal/project/common/image.go
- internal/project/common/lint.go
- internal/project/custom/custom.go
- internal/project/golang/build.go
- internal/project/golang/toolchain.go
- internal/project/golang/unit_tests.go
- internal/project/js/build.go
- internal/project/js/toolchain.go
- internal/project/js/unit_tests.go
- internal/project/service/codecov.go
We can actually assert to the type directly and do not call reflect package functions.
> refactor: dag.Implements not to use reflect package

- Dockerfile
- internal/project/common/image.go
- internal/project/golang/build.go
This also adds a Dockerfile step which combines all Go binaries built for different arches into `<cmd>-all` step.
Example usage:
```yaml
kind: common.Image
name: image-foo
spec:
copyFrom:
- stage: fooctl-all
destination: /assets/fooctl/
```
> feat: introduce an option to copy assets into image from a stage

- go.mod
- go.sum
- internal/project/common/release.go
In some projects, during the CI run the folder `_out/` gets populated we don't want to be published as release artifacts.
This settings allows to customize it to suit our needs.
> feat: allow release artifacts to be specified explicitly

- .dockerignore
- go.mod
- go.sum
- internal/output/dockerfile/dockerfile.go
- internal/output/dockerfile/stage.go
- internal/toposort/toposort.go
- internal/toposort/toposort_test.go
- Add one asterisk instead of two at the beginning of the `.dockerignore` file. This is important because `docker compose` do not understand our current pattern. As for top level `**` and `*` without slashes and characters should make no difference.
- Move toposort into the project, use generics for implementation. Drop type assertions.
> chore: minor fixes and updates

- .gitignore
- .kres.yaml
- internal/project/common/build.go
Now you can add `ignoredPaths` list to `common.Build` spec.
> feat: add support for custom .gitignore paths

- internal/project/js/protobuf.go
Add support for including arbitrary files in the image on `generate-%s` step.
This allows e.g. `make generate-frontend` to bring files into the sources.
Signed-off-by: Utku Ozdemir <utku.ozdemir@siderolabs.com>
> feat: add support for generating arbitrary files

- internal/project/golang/toolchain.go
- internal/project/project.go
This PR adds the ability for kresified repos to use private go libraries by adding a blurb to kres.yaml. Config should look like:
```
kind: golang.Toolchain
spec:
privateRepos:
- github.com/siderolabs/omni-controller
```
Of note, this also adds in the `AfterLoad` ability to be able to edit the ingested config before compilation starts. This allows things like being able to do things like conditionally inject docker build args.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> feat: add ability to build with private git repos

- internal/project/golang/toolchain.go
This PR finalizes the kres support of private libraries. I missed a step of adding the github token to drone's base step so that the git config setup could work as expected.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> fix: add github token to base drone step

- internal/project/common/repository.go
This fixes a fix from 6027a8f55ad4e7e30af4cd9c83197c353395e104 to correctly see that everything is up to date.
> fix: compare status checks correctly

- .drone.yml
- internal/dag/base.go
- internal/dag/node.go
- internal/output/drone/drone.go
- internal/output/drone/pipeline.go
- internal/output/drone/service.go
- internal/project/common/docker.go
- internal/project/custom/custom.go
This allows to run multiple versions of the step in different pipelines with cron schedule and promote rules, saving/loading artifacts on the way.
The design comes from the Talos pipelines.
> feat: provide a way to "split" custom steps into pipelines

- internal/project/custom/custom.go
This PR updates drone setup to remove the immutability policy and tags the azure "containers" (aka buckets) with a ci=true tag. This will allow us to handle the deletion of buckets with the cloud-cleaner app.
> chore: update drone setup to tag azure buckets

- internal/config/constants.go
- internal/project/js/protobuf.go
Fork the plugin to fix some bugs and introduce some reverse incompatible changes which makes sense in our use case.
> chore: drop `ts-proto` usage, use forked version of `grpc-gateway-ts`

- Dockerfile
- go.mod
- go.sum
- internal/config/constants.go
- internal/output/github/github.go
- internal/project/common/repository.go
- github.com/google/go-github/v51 to github.com/google/go-github/v52
- docker.io/node to 20.0.0
> chore: bump deps

- .golangci.yml
- internal/output/golangci/golangci.yml
Since we enabled `GOEXPERIMENT=loopvar` we do not want this check to report errors.
> chore: disable `loopclosure` in `govet`

- Makefile
- internal/project/common/docker.go
It dos not bring any value at the moment, and causing the image to not be linked to a repo on GitHub because the way `LABEL org.opencontainers.image.source` is set when it is enabled.
> feat: disable provenance on buildkit builds

- .github/workflows/ci.yaml
Add a no-op gh workflow so that future PR's can have build status.
> chore: add no-op gh workflow

- Makefile
- internal/project/common/rekres.go
- internal/project/common/repository.go
When error is returned, `resp` might be nil (avoids panic).
Run `rekres` in host networking mode to avoid IPv6 fun issues in Docker.
> fix: handle error returns from GitHub API

- .github/workflows/ci.yaml
- internal/output/ghworkflow/gh_workflow.go
- internal/project/custom/custom.go
Sort the `triggerLabels` for GH custom jobs so that `rekres` always have same output.
Also fix the concurrency.
> fix: custom gh jobs labels sort order

- internal/config/constants.go
The next version contains the fix for timestamps and duration generation.
> chore: bump `protoc-gen-grpc-gateway-ts` library version

- .github/workflows/ci.yaml
- .kres.yaml
- internal/project/common/release.go
This drops `_out/*` as the default asset and uses the auto-detected commands as default.
This is a no-op for custom defined outputs.
> fix: use auto-detected commands as release assets

- cmd/kres/cmd/gen.go
- internal/config/constants.go
- internal/output/dockerfile/dockerfile.go
- internal/output/dockerignore/dockerignore.go
- internal/output/ghworkflow/gh_workflow.go
- internal/output/makefile/group.go
- internal/project/auto/builder.go
- internal/project/auto/golang.go
- internal/project/auto/markdown.go
- internal/project/auto/pkgfile.go
- internal/project/common/all.go
- internal/project/common/build.go
- internal/project/common/repository.go
- internal/project/golang/generate.go
- internal/project/meta/meta.go
- internal/project/pkgfile/build.go
- internal/project/service/codecov.go
This supports `Pkgfile` projects.
Targets can be set as below in `.kres.yaml`:
```yaml
---
kind: pkgfile.Build
spec:
targets:
- toolchain
reproducibleTargetName: toolchain
additionalTargets:
nonfree:
- nonfree-kmod-nvidia-pkg
```
> feat: support pkgfile frontend.

- internal/output/ghworkflow/gh_workflow.go
- internal/project/custom/custom.go
Support running commands with `sudo` in CI.
This is useful for GH actions since default commands run as `runner` user.
> chore: support sudo in CI

- .github/workflows/ci.yaml
- internal/output/ghworkflow/gh_workflow.go
Moving to using github script means we need perms to get issues.
> fix: add missing workflow permission.

- internal/project/custom/custom.go
- internal/project/pkgfile/build.go
Fixes the pull request label retrieve step condition to only run on pull requests.
Also fix the download artifacts steps to be only enabled if artifacts are enabled.
> fix: pull request label step condition

- internal/output/ghworkflow/types.go
- internal/project/custom/custom.go
Support ignoring artifact upload failures with GitHub actions.
> chore: support ignoring artifact upload failures

- internal/project/custom/custom.go
Support conditions for custom GitHub action job steps. Also fix adding the `retrieve-pr-labels` step twice when custom jobs are enabled.
> chore: support conditions for custom gh steps

- internal/project/golang/govulncheck.go
See https://github.com/golang/go/issues/64112
> fix: allow `lint-govulncheck` to be disabled

- internal/output/ghworkflow/gh_workflow.go
- internal/project/custom/custom.go
- internal/project/pkgfile/build.go
This fixes the gh job outputs to return an empty `[]` string if the event is not a pull request. This would fix the GH job failing to evaluate the dependent job condition.
> fix: gh job outputs

- .golangci.yml
- Makefile
- cmd/kres/cmd/gen.go
- cmd/kres/cmd/version.go
- internal/config/constants.go
- internal/output/golangci/golangci.yml
- internal/output/makefile/makefile.go
- internal/project/auto/golang.go
- internal/project/golang/toolchain.go
While I was bumping it to v1.56.0 they released v1.56.1 with more fixes for Go 1.22. So we do a small update.
Also:
- Remove `loopclosure` analysis from disabled list because it's disabled by default for Go >= 1.22.
- Per Go 1.22 release notes "GO_LDFLAGS" "-s -w" and "-s" are equivalent, so move to the latter.
> chore: bump golangci-lint to v1.56.1

- cmd/kres/cmd/gen.go
- internal/output/ghworkflow/gh_workflow.go
- internal/project/common/repository.go
This helps to handle the case when the main branch is `v2` (for Go modules).
> feat: add better support for custom main branch

- Makefile
- internal/project/common/build.go
Treat only semver tags as valid tags.
> fix: make `TAG` getter select only tags starting with `v` prefix

- .github/workflows/ci.yaml
- internal/output/ghworkflow/gh_workflow.go
Looking logs I suspect this is just something to do with IPv6. So explicitly use IPv4 address when connecting.
> fix: buildx setup

- .github/workflows/ci.yaml
- internal/output/ghworkflow/gh_workflow.go
One minute can be too short, so bump it to 10 minutes.
> feat: bump gh actions buildx setup timeout minutes

- internal/project/pkgfile/build.go
Since repository name must be lowercase it was not possible for users / orgs containing uppercase letter to use Kres
> fix: Allow repository owner to contains uppercase characters

- .github/workflows/ci.yaml
- Makefile
- internal/project/common/build.go
- internal/project/common/image.go
- internal/project/common/makehelp.go
This fixes the version of the `:latest` image not to be `latest`, but a proper matching version.
See https://github.com/siderolabs/omni/issues/131
> fix: split `TAG` and `IMAGE_TAG` veriables

- internal/output/conform/commitpolicy/commitpolicy.go
- internal/output/conform/conform.go
- internal/project/common/repository.go
Required for release/backport branches.
> fix: allow conform 'max one commit' to be disabled

- .github/workflows/ci.yaml
- Makefile
- internal/config/constants.go
- internal/project/service/codecov.go
Use the official codecov action, since the bash script is deprecated. Also set a timeout on upload so we don't block other steps for too long.
> fix: codecov upload

- .github/workflows/ci.yaml
- Makefile
- cmd/kres/cmd/gen.go
- internal/config/constants.go
- internal/output/ghworkflow/gh_workflow.go
- internal/output/ghworkflow/types.go
- internal/project/auto/builder.go
- internal/project/auto/ci.go
- internal/project/auto/config.go
- internal/project/common/build.go
- internal/project/common/gh_workflow.go
- internal/project/common/image.go
- internal/project/common/lint.go
- internal/project/common/release.go
- internal/project/custom/custom.go
- internal/project/golang/build.go
- internal/project/golang/toolchain.go
- internal/project/golang/unit_tests.go
- internal/project/js/build.go
- internal/project/js/toolchain.go
- internal/project/js/unit_tests.go
- internal/project/meta/meta.go
- internal/project/pkgfile/build.go
- internal/project/service/codecov.go
Support managing only GitHub workflows.
This still handles SOPS, conform and repository checks.
Can be enabled with:
```yaml
---
kind: auto.CI
spec:
compileGHWorkflowsOnly: true
```
> feat: add support for gh workflow only kres

- Makefile
- internal/project/common/build.go
- internal/project/pkgfile/build.go
`SOURCE_DATE_EPOCH` is only used by `Pkgfile` based projects and it has to be a consistent value for easy reproducibility.
> fix: source date epoch value.

- .github/workflows/ci.yaml
- internal/output/ghworkflow/gh_workflow.go
- internal/project/auto/ci.go
- internal/project/auto/config.go
- internal/project/common/gh_workflow.go
- internal/project/custom/custom.go
- internal/project/pkgfile/build.go
Use existing amd64 buildx runners.
Also support overriding default runners.
> chore: use existing amd64 buildx

- internal/project/common/repository.go
- internal/project/common/sops.go
Only enable adding sops if it's a standard kres project, for github workflow managed by kres, it's part of job spec.
> fix: enable sops step only for standard kres steps

- internal/output/dockerfile/stage.go
- internal/project/js/build.go
- internal/project/js/toolchain.go
Do not run npm on arm64 as it's ineffective.
> chore: generate Dockerfile with BUILDPLATFORM for frontend tasks

- Dockerfile
- internal/project/golang/toolchain.go
Set `BUILDPLATFROM` so that we re-use the toolchain.
> fix: go cross compile images

- internal/project/js/toolchain.go
Verify can check that all required packages are installed and fail the step if something is missing so that it won't be cached.
> fix: run verify as part of `npm ci` step

- .golangci.yml
- internal/output/golangci/golangci.yml
- internal/project/common/repository.go
- Add depguard back since it allows functionality similar to `denylist`.
- Remove fully deprecated and disabled linters from `linters.disable` section.
> chore: cleanup .golangci.yml

- .golangci.yml
- internal/project/golang/generate.go
Split tools for go generate and protobuf generate.
> fix: install goimports if go generate is used

- internal/project/markdown/lint.go
It works without it, while adding this flag breaks it.
> fix: remove `-g` flag from the bun install for the lint markdown step

- Dockerfile
- internal/output/dockerfile/step/env.go
- internal/output/dockerfile/step/label.go
- internal/output/dockerfile/step/step_test.go
New dockerfile frontend emits warnings about using old syntax.
> fix: use updated ENV & LABEL syntax

- .golangci.yml
- .kres.yaml
- internal/output/golangci/golangci.go
- internal/output/golangci/golangci.yml
- internal/project/golang/golangcilint.go
Allow projects to define additional `depguard` rules in their `.kres.yaml`.
To be used by https://github.com/siderolabs/omni/issues/373.
> feat: allow additional `depguard` golangci-lint rules

- internal/project/pkgfile/build.go
Skip building again on PR merges for `Pkgfile` based repos, this should force it to re-use cache if available.
> chore: pkgfile skip build on merges.

- internal/project/auto/golang.go
Allow a mix of standard and non-standard directories.
This is now the recommended approach: https://go.dev/doc/modules/layout
(This skips `pkg/` for public parts).
> fix: be more flexible on Go project structure

- internal/config/constants.go
> chore: bump moby/buildkit to v0.15.1

- hack/release.sh
- internal/output/files.go
- internal/output/release/release.go
Ensures the hack/release.sh script is more portable by using the /usr/bin/env shebang.
> feat: make release script portable

- Makefile
- internal/project/common/docker.go
- internal/project/pkgfile/build.go
Passing `BUILDKIT_MULTI_PLATFORM=1` to buildkit for each build (introduced in https://github.com/siderolabs/kres/commit/7db4f5e2647e1bbccf6915ff3d84a0754e1b5057) in `COMMON_ARGS` caused some unwanted changes in the output behavior when we ran a single-platform build: it started to output the files to locations same as to multi-platform format, `<os>_<arch>/<filename>`, instead of just `<filename>`.
Fix this by running a small script to move these files to one upper directory after a local build.
> fix: fix local artifact output locations when `BUILDKIT_MULTI_PLATFORM=1`

- .golangci.yml
- Makefile
- internal/output/golangci/golangci.yml
- internal/project/golang/generate.go
Due to the change in `BUILDKIT_MULTI_PLATFORM=1`, the generated files from `make generate` land initially in a directory named `<os>_<arch>`, which we then move into the actual destination directories with a script.
This move fails to merge the existing directories with the newly generated files. So, instead, on `generate` command, we override the `BUILDKIT_MULTI_PLATFORM` variable back to `0` to restore the old behavior. We do not need it for generating sources.
Additionally, remove the deprecated `gomnd` linter from the `golangci-lint` configuration.
> fix: fix `make generate` to build with `BUILDKIT_MULTI_PLATFORM=0`

- Makefile
- internal/project/common/docker.go
- internal/project/golang/generate.go
- internal/project/pkgfile/build.go
This allows to properly override it on per-target basis.
This is required to fix kernel build in pkgs.
> fix: make `BULDKIT_MULTIPLATFORM` a make variable

- internal/project/js/protobuf.go
Same fix as in 91b35db66814d3687233e0eb5987e777210d795d, a8af16daf5f0d7c9a61d81218820de7f0c407f97, but for the JS definitions.
> fix: disable `BUILDKIT_MULTI_PLATFORM` for JS protobuf generation

- Makefile
- internal/project/common/docker.go
Do a force move, so that `mv` command will not prompt to overwrite in any circumstance.
> fix: ensure non-interactive move when fixing local output destinations

- .github/renovate.json
- internal/output/renovate/types.go
- internal/project/common/renovate.go
Add more renovate config options.
> chore: add more renovate config options

- internal/output/renovate/types.go
- internal/project/common/renovate.go
`matchFiles` is removed in favor of `matchFileNames`.
> fix: renovate config option

- .github/renovate.json
- internal/output/renovate/renovate.go
- internal/output/renovate/types.go
- internal/project/common/renovate.go
Also add `allowedVersions` field.
> fix: renovate preamble.

- internal/project/common/gh_workflow.go
- internal/project/custom/custom.go
Support setting custom retention time for upload artifacts. If not set default to `5d`.
> chore: support custom retention time

- .conform.yaml
- .golangci.yml
- Dockerfile
- Makefile
- internal/output/golangci/golangci.yml
The linter "exportloopref" is deprecated and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
related: https://github.com/siderolabs/omni/pull/950
> chore: remove deprecated linter

- internal/config/constants.go
- internal/output/ghworkflow/gh_workflow.go
- internal/project/common/gh_workflow.go
- internal/project/pkgfile/build.go
Use same buildkit for pkgs and other builds. Stop using sub-volumes for caches.
> feat: unify buildkits

- Dockerfile
- internal/output/dockerfile/step/run.go
- internal/output/dockerfile/step/step_test.go
- internal/project/custom/custom.go
- internal/project/golang/build.go
- internal/project/golang/deepcopy.go
- internal/project/golang/generate.go
- internal/project/golang/golangcilint.go
- internal/project/golang/govulncheck.go
- internal/project/golang/linters.go
- internal/project/golang/toolchain.go
- internal/project/golang/unit_tests.go
- internal/project/js/build.go
- internal/project/js/eslint.go
- internal/project/js/protobuf.go
- internal/project/js/toolchain.go
- internal/project/js/unit_tests.go
Otherwise by default cache ID is just `target` path, so all caches from all projects go into the same object.
Also lock the linter cache, as I don't think it supports concurrent writes.
See https://docs.docker.com/reference/dockerfile/#run---mounttypecache
> fix: use project-specific cache IDs per project

- Dockerfile
- internal/project/golang/golangcilint.go
They use upstream version of json validation, and currently are issuing breaking V2 release
https://github.com/golangci/golangci-lint/commit/f1f8343d12ac33720efeb5898141d1e065789751
We will add it back, once we complete our migration to v2.
> chore: remove golangci-lint config verify

- .golangci.yml
- internal/output/golangci/golangci.yml
It gives false positives, failing CI runs - see https://github.com/golangci/golangci-lint/issues/3228#issuecomment-2796615846.
> fix: disable `nolintlint` linter

- internal/project/pkgfile/build.go
Fix renovate `managerFilePatterns` for explicit declarations.
> fix: renovate `managerFilePatterns`

- .github/workflows/ci.yaml
- Dockerfile
- go.mod
- go.sum
- internal/config/constants.go
- internal/output/github/github.go
- internal/project/common/repository.go
| Package | Type | Update | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|---|---|
| docker |  | minor | `28.1-dind` -> `28.2-dind` | [![age](https://developer.mend.io/api/mc/badges/age/docker/docker/28.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/docker/docker/28.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/docker/docker/28.1/28.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/docker/docker/28.1/28.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| …
> feat: update dependencies

- internal/project/auto/config.go
- internal/project/auto/integration_tests.go
By default it still falls back to the same name as the integration test step.
> feat: support custom image names in the integration tests targets

- Dockerfile
- internal/project/golang/unit_tests.go
Disable `-v` and `-count 1` by default. They can be re-enabled if needed via:
```
kind: golang.UnitTests
name: unit-tests
spec:
verbose: true
count: 1
```
> feat: remove `-v` and `-count 1` from unit tests run

- .github/workflows/ci.yaml
- internal/project/common/gh_workflow.go
- internal/project/common/release.go
There was a missing `cd _out` which breaks it.
Also use `--output-signature` flag, as `--output` got deprecated.
> fix: checksum sign step

- internal/project/auto/js.go
- internal/project/js/toolchain.go
In some configuration `Vite` assets can be stored in the `public` dir instead of the `frontend` root.
> feat: include `frontend/public` dir into the docker build

- Dockerfile
- internal/project/golang/govulncheck.go
Update dockerfile instruction order for govulncheck.sh
> fix: update dockerfile instruction order for govulncheck

- .github/workflows/ci.yaml
- internal/config/constants.go
- internal/output/ghworkflow/gh_workflow_test.go
Rollback `kenchan0130/actions-system-info` to v1.3.1 from v1.4.0.
Reason for this is: with v1.4.0 this action started using `node` 24 and this was causing intermittent issues on CI runs.
> fix: rollack actions-system-info GH action to previous version

- internal/output/dockerfile/step/copy.go
- internal/project/js/eslint.go
Adds a fmt-frontend command to the makefiles to run lint:fix from inside docker.
Fixes https://github.com/siderolabs/kres/issues/549
Related:
- https://github.com/siderolabs/omni/pull/1425
> chore: add fmt-frontend command to run lint:fix

- Makefile
- internal/project/common/lint.go
- internal/project/golang/golangcilint.go
- internal/project/js/eslint.go
It runs all linters which can format code in a row.
> feat: add `lint-fmt` target

- internal/dag/base.go
- internal/dag/node.go
- internal/project/golang/build.go
- internal/project/golang/toolchain.go
Previously it was attached to the `base`, so it got into steps like `golangci-lint` which don't care about it, but also it gets exported back to the source tree via `make lint-golangci-lint-fmt`.
Re-attach it to the build step (where we actually need it).
Another solution is to make it part of `make generate` and keep it part of the source tree.
> fix: make JS frontend target attach to the build

- internal/project/custom/custom.go
Always retrieve PR labels on default job
> fix: always retrieve PR labels on default job

- .github/renovate.json
- .github/workflows/ci.yaml
- .kres.yaml
- internal/config/constants.go
- internal/output/ghworkflow/gh_workflow.go
- internal/project/common/gh_workflow.go
- internal/project/common/release.go
- internal/project/custom/custom.go
- internal/project/meta/meta.go
- internal/project/pkgfile/build.go
Allow defining GH Action Workflow jobs as dispatchable meaning they will run only on a workflow_dispatch event.
Example usage:
- https://github.com/siderolabs/talos/pull/11875
Signed-off-by: Mateusz Urbanek <mateusz.urbanek@siderolabs.com>
> feat: add dispatchable actions

- internal/output/ghworkflow/gh_workflow.go
- internal/project/common/gh_workflow.go
- internal/project/custom/custom.go
- internal/project/pkgfile/build.go
Allow defining inputs by name in the dispatchable workflows.
Signed-off-by: Mateusz Urbanek <mateusz.urbanek@siderolabs.com>
> feat: add inputs to gh_workflow
